[package]
name = "fund-concert"
version = "0.0.1"
authors = ["Juan David Nicholls", "Wbert Castro <@dobleuber>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"